add_newline = true

[aws]
symbol = " "

[cmd_duration]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 100
truncate_to_repo = false

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
disabled = false
ssh_only = false

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabeled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[username]
disabled = false
show_always = true
format = "[$user]($style) at "
style_user = "bold purple"
